## Assignment 6

In [51]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from zipfile import ZipFile
%matplotlib inline

### 1. Decicision Trees

In [77]:
def load_data():
    data = np.array(pd.read_csv('spambase/spambase.data', sep=',', header=None))
    X = np.arraydata[:,0:-1]
    y = data[:,-1]
    return X, y

In [82]:
X, y = load_data()
print(X)

[[0.000e+00 6.400e-01 6.400e-01 ... 3.756e+00 6.100e+01 2.780e+02]
 [2.100e-01 2.800e-01 5.000e-01 ... 5.114e+00 1.010e+02 1.028e+03]
 [6.000e-02 0.000e+00 7.100e-01 ... 9.821e+00 4.850e+02 2.259e+03]
 ...
 [3.000e-01 0.000e+00 3.000e-01 ... 1.404e+00 6.000e+00 1.180e+02]
 [9.600e-01 0.000e+00 0.000e+00 ... 1.147e+00 5.000e+00 7.800e+01]
 [0.000e+00 0.000e+00 6.500e-01 ... 1.250e+00 5.000e+00 4.000e+01]]


### c) Can Information Gain be negative?