## Assignement 2 - Least-Squares Linear Regression

In [68]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [69]:
training_data = np.array(pd.read_csv('zip.train', sep=' ', header=None))
test_data = np.array(pd.read_csv('zip.test', sep =' ',header=None))

x_train, y_train = training_data[:,1:-1], training_data[:,0]
x_test, y_test = test_data[:,1:], test_data[:,0]

In [70]:
def labels_to_one_hot(labels):
    onehot_encoded = []
    for label in labels:
        vector = np.zeros(10)
        vector[int(label)] = 1
        onehot_encoded.append(vector)
    return np.array(onehot_encoded)

In [87]:
y_train_vec = labels_to_one_hot(y_train)

In [88]:
def estimate_b(X, y):
    invXtX = np.linalg.inv(np.dot(np.transpose(X), X))
    return np.dot(np.dot(invXtX, np.transpose(X)), y)

In [89]:
b = estimate_b(x_train, y_train_vec)

In [90]:
y_hat = np.dot(x_test, b)
prediction = y_hat.argmax(axis=1)

In [91]:
accuracy = np.mean(y_test == prediction)
print(accuracy)

0.869955156951


In [95]:
def confusion_matrix(labels, predictions):
    size = len(set(labels))
    matrix = np.zeros((size, size))
    for correct, predicted in zip(labels.astype(int), predictions):
        matrix[correct][predicted] += 1
    return matrix

In [97]:
print(confusion_matrix(y_test, prediction))

[[ 347.    2.    0.    1.    3.    1.    4.    0.    0.    1.]
 [   0.  254.    0.    2.    3.    0.    3.    0.    1.    1.]
 [   7.    3.  159.    8.   10.    1.    1.    1.    8.    0.]
 [   5.    0.    4.  137.    2.    9.    0.    2.    3.    4.]
 [   3.    7.    4.    0.  169.    1.    3.    2.    1.   10.]
 [   9.    1.    0.   20.    2.  122.    0.    1.    1.    4.]
 [   3.    2.    4.    0.    5.    4.  151.    0.    1.    0.]
 [   3.    1.    1.    1.    7.    0.    0.  130.    0.    4.]
 [   8.    3.    3.   15.    3.    8.    1.    2.  119.    4.]
 [   0.    3.    0.    0.    7.    0.    0.    7.    2.  158.]]
